port = 3030

[env.common]
THE_SECRET = { encrypted = "jsAMmb2m1RtkDtwY7arXhI3Lsx_RuEhllS-MuW2ZkAqYak_If2Q7iwIXp0KCar6x8HM7Dok4v8nku8InaVDohAVlIMr6ug9IO86j9V_4NqrRg-zwsPyu0O17PywNNUiA3fcT-za_0452QM8iGY60vHXSq_sBpESEEQ84fIERfgn4MqSOvk9xHEdcYHP0SoQk232KICKctFmiU2o754YwXeCqggXV3kkL9FmZw1Y0c3Hj20zDgibQuiL_DNRt2kcXAnAziplUxnhSDf5NjF5oH6HFVLVrL94hNsTj9aip6gkW6YTmI2zylxmYqYP5wuX23SjHBsHValrglq1S4ELMlT2y" }
